instagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('posts/',include('posts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

posts/urls.py
from django.contrib import admin
from django.urls import path

from . import views
from posts.views import PostListView,PostDetailView

app_name = 'posts'
urlpatterns=[
    path('new/',views.post, name= 'post_new'),
    path('post_list/',PostListView.as_view(), name='post_list'),
    path('post_list/<int:pk>',PostDetailView.as_view(), name='post_detail'),

]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    caption = models.CharField(max_length=200)
    image = models.ImageField(upload_to='post_image', height_field=None, width_field=None, max_length=100, default="Sorry")
    # people = models.CharField(max_length=300, default="None")
    # likes = models.IntegerField(default=0)
    post_date = models.DateField(auto_now=False, auto_now_add= False, default =timezone.now)

    def __str__(self):
        return self.caption

    def get_absolute_url(self):
        return reverse('posts:post_detail', args=[str(self.id)])

    class Meta:
        ordering = ['-post_date']

class Feed(models.Model):
    name = models.CharField(max_length=80)
    no_of_followers = models.IntegerField(default=0)

    def __str__(self):
        return self.name
        
class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete= models.CASCADE)
    text = models.TextField()
    create_date = models.DateTimeField(auto_now=False, auto_now_add=True)

posts/forms.py
from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
from .models import  Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image','caption',]

posts/views.py
from django.shortcuts import render, redirect
from .forms import PostForm
from posts.models import Post
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


@login_required
def post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            # form.save()
            return redirect('posts:post_list')
    else:
        form = PostForm()
    return render(request, 'posts/post_form.html', {'form': form})


class PostListView(ListView):
    model = Post


class PostDetailView(DetailView):
    model = Post

templates/posts/like.html
{% extends 'account/base.html' %}

{% block content %}

{% if user.is_authenticated %}
    {% if request.user in post.user.all %}
    <a href="#" id="itemLike{{ item.id }}" data-rating=""><i class="fa fa-heart fa-2x text-
        liked" id="heart-icon{{ item.id }}"></i></a>
        <b id="like-count{{ item.id }}" class="like-
        count">{{ item.rating_count }}</b>
    {% else %}
		<a href="#" id="itemLike{{ item.id }}" data-rating=""><i class="fa fa-heart-o fa-2x text-
         not-liked" id="heart-icon{{ item.id }}"></i></a><b id="like-count{{ item.id }}" 
         class="like-count">{{ item.rating_count }}</b>
	{% endif %}
	{% else %}
		<a href="#" data-toggle="modal" data-target="#login-modal" data-rating=""><i class="fa fa-
         heart-o fa-2x"></i></a>
{% endif %}

{% endblock %}

templates/posts/post_detail.html
{% extends 'account/base.html' %}
{% block content %}

<div class="container">
    <h3>Your Post.!</h3>
    <p>User: {{ user }}</p>
    {% if post.image %}
    <img src="{{ post.image.url }}" width="240">
    {% endif %}
    <p>{{ post.post_date }}</p>
    <p>{{ post.caption }}</p>
    <form action="{% url 'posts:post_list' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Like</button>
    </form>
  
</div>
{% endblock %}

templates/posts/post_form.html
{% extends 'account/base.html' %}

{% load bootstrap4 %}
{% block content %}

{% if user.is_authenticated %}
<h4>Create a new Post.!</h4>
<form id="postForm"  method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.errors }}
    {% bootstrap_form form %}
    <input type="submit" value="Save" class="btn btn-primary btn-large">
</form>
{% else %}
        <a href="{% url 'login' %}?next={{ request.path }}">Login to Post.!</a>
{% endif %}

{% endblock %}

templates/posts/post_list.html
{% extends 'account/base.html' %}
{% block content %}
  <h1>Post List</h1>
  {% if post_list  %}
  <ul>
    {% for post in post_list %}
      <li>
        <!-- <a href="{{ post.get_absolute_url }}">{{ post.image }}</a> ({{ post.caption }}) -->
        {% if post.image %}
        <img src="{{ post.image.url }}" width="240">
        {% endif %}
        <p>{{ post.post_date }}</p>
        <p>{{ post.caption }}</p>
        <p>{{ post.user }}</p>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No Posts :(</p>
    <p><a href="{% url 'posts:post_new' %}">Make a Post?</a>:)</p>
  {% endif %}       
{% endblock %}